export let GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING";
export let GET_PRODUCT_SECCESS = "GET_PRODUCT_SUCCESS";
export let GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export let POST_PRODUCT_PENDING = "POST_PRODUCT_PENDING";
export let POST_PRODUCT_SECCESS = "POST_PRODUCT_SUCCESS";
export let POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";

export let DELETE_PRODUCT_PENDING = "DELETE_PRODUCT_PENDING";
export let DELETE_PRODUCT_SECCESS = "DELETE_PRODUCT_SUCCESS";
export let DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export let UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT_PENDING";
export let UPDATE_PRODUCT_SECCESS = "UPDATE_PRODUCT_SUCCESS";
export let UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";